name: round_icon
description: An icon widget with a circular background.
version: 0.0.2
homepage: https://github.com/teixeirazeus/round_icon
repository: https://github.com/teixeirazeus/round_icon

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

